### ISSUE TITLE
App uses OAuth1

### ISSUE THREAD

**Issue by davidjwiner** [IntuitDeveloper/SampleApp-InventoryTracking-QuickBooksV3API-NodeJS#2]
It looks like this app uses the old OAuth1 workflow, which is no longer permitted by new apps/accounts on developer.intuit.com.

**Comment by diana-derose** [comment]
Hi David, please refer to the following repo for OAuth2 sample. 
https://github.com/IntuitDeveloper/oauth2-nodejs
We will be updating this one to add oauth2 soon.

**Comment by webcoma3logics** [comment]
How can I implement OAuth2 in this sample app ? is there any example or steps for that?

**Comment by diana-derose** [comment]
Hi - You can either use the sample mentioned above or use the one below for oauth2. https://github.com/IntuitDeveloper/OAuth2.0-demo-nodejs
